export const wheelConfig = {
  slots: 21,
  centerX: 400,
  spinDuration: 5000,
  spinDeceleration: 0.95,
  centerY: 400,
  outerRadius: 540,
  innerRadius: 370,
  gapWidth: 10,
  cornerRadius: 15,
  randomOffset: 8,
  prizes: [
    { image: 'bear.svg', value: '15', chance: 9, multiplier: 0.6, type: 'win' },
    { image: 'bear.svg', value: '15', chance: 9, multiplier: 0.6, type: 'win' },
    { image: 'rose.svg', value: '25', chance: 15, multiplier: 1, type: 'win' },
    { image: 'bust.svg', value: 'Буст', chance: 12, multiplier: 0, type: 'boost' },
    { image: 'heart.svg', value: '15', chance: 9, multiplier: 0.6, type: 'win' },
    { image: 'flowers.svg', value: '50', chance: 8, multiplier: 2, type: 'win' },
    { image: 'diamond.svg', value: '100', chance: 3, multiplier: 4, type: 'win' },
    { image: 'gift.svg', value: '25', chance: 15, multiplier: 1, type: 'win' },
    { image: 'rocket.svg', value: '50', chance: 8, multiplier: 2, type: 'win' },
    { image: 'bear.svg', value: '15', chance: 9, multiplier: 0.6, type: 'win' },
    { image: 'heart.svg', value: '15', chance: 9, multiplier: 0.6, type: 'win' },
    { image: 'ring.svg', value: '100', chance: 3, multiplier: 4, type: 'win' },
    { image: 'rose.svg', value: '25', chance: 15, multiplier: 1, type: 'win' },
    { image: 'bust.svg', value: 'Буст', chance: 12, multiplier: 0, type: 'boost' },
    { image: 'trophy.svg', value: '100', chance: 3, multiplier: 4, type: 'win' },
    { image: 'bear.svg', value: '15', chance: 9, multiplier: 0.6, type: 'win' },
    { image: 'rose.svg', value: '25', chance: 15, multiplier: 1, type: 'win' },
    { image: 'flowers.svg', value: '50', chance: 8, multiplier: 2, type: 'win' },
    { image: 'gift.svg', value: '25', chance: 15, multiplier: 1, type: 'win' },
    { image: 'snake.svg', value: '400', chance: 0.5, multiplier: 16, type: 'win' },
    { image: 'rose.svg', value: '25', chance: 15, multiplier: 1, type: 'win' }
  ]
};
